--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: administradores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.administradores (
    "Id" integer NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Senha" character varying(50) NOT NULL,
    "Perfil" character varying(10) NOT NULL
);


ALTER TABLE public.administradores OWNER TO postgres;

--
-- Name: administradores_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.administradores ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."administradores_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: administradores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.administradores ("Id", "Email", "Senha", "Perfil") FROM stdin;
1	administrador@teste.com	123456	Adm
2	adm@adm.com	123456	Editor
\.


--
-- Name: administradores_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."administradores_Id_seq"', 2, true);


--
-- Name: administradores PK_administradores; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT "PK_administradores" PRIMARY KEY ("Id");


--
-- PostgreSQL database dump complete
--

