--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: veiculos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.veiculos (
    "Id" integer NOT NULL,
    "Nome" character varying(150) NOT NULL,
    "Marca" character varying(100) NOT NULL,
    "Ano" integer NOT NULL
);


ALTER TABLE public.veiculos OWNER TO postgres;

--
-- Name: veiculos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.veiculos ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."veiculos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: veiculos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.veiculos ("Id", "Nome", "Marca", "Ano") FROM stdin;
3	Marea Turbo	Ford	2001
\.


--
-- Name: veiculos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."veiculos_Id_seq"', 3, true);


--
-- Name: veiculos PK_veiculos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.veiculos
    ADD CONSTRAINT "PK_veiculos" PRIMARY KEY ("Id");


--
-- PostgreSQL database dump complete
--

